# Generated by Django 3.1.1 on 2020-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=100)),
                ('user_validate', models.BooleanField(default=False)),
                ('user_phonenumber', models.CharField(max_length=15)),
            ],
        ),
    ]
